{% set version = "1.1.0" %}

package:
  name: nifty
  version: {{ version }}

source:
  url: https://github.com/DerThorsten/nifty/archive/v{{ version }}.tar.gz
  sha256: ff61ef2394c739bf3672ae313f11dc43117671ded3b7924d1c94fc407ccd42ae

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make
  host:
    - python
    - numpy
    - xtensor >=0.21,<0.22
    - xtensor-python >=0.24,<0.25
    - vigra 1.11.1=*_1026
    # vigra should pull in hdf5 dependency
    # - vigra
    # - hdf5
    - z5py >=2.0.11
    # build dependencies needed for z5
    - nlohmann_json
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-image

test:
  imports:
    - nifty
    - nifty.graph
    - nifty.distributed  # [not win]
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
  requires:
    - z5py

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  license_file: LICENSE
  summary: nifty

extra:
  recipe-maintainers:
    - constantinpape
    - DerThorsten
